name: 'Push build to QA repository'

inputs:
  branch_name: 
    description: 'Branch name to push to'
    required: true
  commit_message: 
    description: 'Commit message for the push'
    required: true
  pat_token:
    description: "QA repository PAT token"
    required: true
  build_folder:
    description: "Path to the build directory"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Create branch in another repository and copy files
      env:
        REPO_TOKEN: ${{ inputs.pat_token }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        BUILD_FOLDER: ${{ inputs.build_folder }}
      run: |
        TARGET_REPO="github.com/zeriontech/zerion-wallet-extension-qa.git"
        BRANCH_NAME="${{ github.head_ref || github.ref_name }}"

        git config --global user.email "zerts@zerion.io"
        git config --global user.name "QA Bot"

        # Clone the target repository
        git clone "https://${REPO_TOKEN}@${TARGET_REPO}" qa-repository
        cd qa-repository

        # Create or switch to the new branch
        git checkout "$BRANCH_NAME" || git checkout -b "$BRANCH_NAME"

        # Pull the latest changes from the remote branch if it exists
        if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH_NAME"; then
          git pull origin "$BRANCH_NAME"
        fi

        # Copy files from the dist directory
          mkdir -p "$BUILD_FOLDER"
          cp -r ../dist/* "$BUILD_FOLDER"   # Commit and push changes
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "$COMMIT_MESSAGE"
        git push origin "$BRANCH_NAME"
      shell: bash
