export const noValueDash = '—';
export const emDash = '—';
export const minus = '\u2212'; // '−'; // \u2212
export const apostrophe = '’';
export const ellipsis = '…';
export const NBSP = '\u00a0';
export const muchGreater = '≫';
export const veryMuchGreater = '⋙';
export const almostEqual = '\u2248';
