name: Build pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Install dependencies and build
        env:
          ALCHEMY_KEY: RKg5wIwcuh32powb0blKdPh0UwSsgmFI
          DEFI_SDK_API_URL: wss://api-v4.zerion.io/
          DEFI_SDK_API_TOKEN: Zerion.0JOY6zZTTw6yl5Cvz9sdmXc7d5AhzVMG
          SOCIAL_API_URL: https://social.zerion.io/
        run: |
          npm install
          npm run build:production

      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/

      - name: Compress build artifacts
        shell: bash
        run: |
          mv dist zerion-wallet-extension-${{github.sha}}
          zip -r zerion-wallet-extension-${{github.sha}}.zip zerion-wallet-extension-${{github.sha}}
          tar czf zerion-wallet-extension-${{github.sha}}.tar.gz --directory=zerion-wallet-extension-${{github.sha}} .

      - name: Upload build
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: zerion-wallet-extension
          path: zerion-wallet-extension-${{github.sha}}.zip
