name: Notify release

on:
  workflow_run:
    workflows:
      - Create release
    types:
      - completed

jobs:
  notify_release:
    runs-on: ubuntu-latest
    steps:
      - name: Notify release
        id: notify-release
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04KLJV3HFV'
          payload: |
            {
              "text": "New release",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":gift: Release ${{ github.ref_name }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Created by:* ${{ github.triggering_actor }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ format('{0}/{1}/{2}/releases/tag/{3}', github.server_url, github.repository, github.ref_name)}}|${{ github.ref_name }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
