name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pull_reuqest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Install dependencies and build
        env:
          ALCHEMY_KEY: RKg5wIwcuh32powb0blKdPh0UwSsgmFI
          DEFI_SDK_API_URL: wss://api-v4.zerion.io/
          DEFI_SDK_API_TOKEN: Zerion.0JOY6zZTTw6yl5Cvz9sdmXc7d5AhzVMG
          SOCIAL_API_URL: https://social.zerion.io/
        run: |
          npm install
          npm run build:production

      - name: Compress build artifacts
        shell: bash
        run: |
          mv dist zerion-wallet-extension-${{github.sha}}
          zip -r zerion-wallet-extension-${{github.sha}}.zip zerion-wallet-extension-${{github.sha}}
          tar czf zerion-wallet-extension-${{github.sha}}.tar.gz --directory=zerion-wallet-extension-${{github.sha}} .

      - name: Notify build succeeded
        id: notify-build-succeeded
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04JLLQRB43'
          payload: |
            {
              "text": "Build succeeded",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rocket: Build succeeded"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Initiated by:* ${{ github.triggering_actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Attempt:* ${{ github.run_attempt }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ format('{0}/{1}/{2}', github.server_url, github.repository, github.event.number)}}|${{ github.ref_name }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}

      - name: Notify build failed
        id: notify-build-failed
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04JLLQRB43'
          payload: |
            {
              "text": "Build failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":x: Build failed"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Initiated by: ${{ github.triggering_actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Attempt:* ${{ github.run_attempt }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ format('{0}/{1}/{2}', github.server_url, github.repository, github.event.number)}}|${{ github.ref_name }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: zerion-wallet-extension
          path: |
            zerion-wallet-extension-${{github.sha}}.zip
            zerion-wallet-extension-${{github.sha}}.tar.gz
